package wid.bmsbackend.entity;

public enum DeviceCommandType {
    PULSE_START_REQUEST, PULSE_START_PROCESSED, PULSE_STOP_REQUEST, PULSE_STOP_PROCESSED,
    CELL_BALANCING_START_REQUEST, CELL_BALANCING_START_PROCESSED, CELL_BALANCING_STOP_REQUEST, CELL_BALANCING_STOP_PROCESSED,
}
